defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  timeout: 5000
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>

development:
  database: application_dev
  <<: *defaults

test:
  database: application_test
  <<: *defaults

production: &deploy
  <<: *defaults

staging: *deploy
